name: telegram-welcome-bot
env:
  API_ID: "your_api_id"
  API_HASH: "your_api_hash"
  BOT_TOKEN: "your_bot_token"
build:
  envs:
    - python3
  command: pip install -r requirements.txt
run:
  command: python3 bot.py